
[font]
normal = { family = "FiraCode Nerd Font", style = "SemiBold" }
bold = { family = "FiraCode Nerd Font", style = "SemiBold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 11.5  


[env]
LANG = "en_US.UTF-8"
TERM = "xterm-256color"
