[font]
normal = { family = "FiraCode Nerd Font", style = "SemiBold" }
bold = { family = "FiraCode Nerd Font", style = "SemiBold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 11.5  


[env]
LANG = "en_US.UTF-8"
TERM = "xterm-256color"


[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]

[terminal.shell]
program = "C:\\Users\\Lenovo\\AppData\\Local\\Programs\\nu\\bin\\nu.exe"  # Path to Nushell
args = ["--login"]  
